### ISSUE TITLE
Variability in gene expression between sACC and AMYG

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/zandiHyde_bipolar_rnaseq#13]
> 5. Regarding the difference between the number of differentially expressed features in sACC and amygdala, are expression levels (of any/all features) more variable in the sACC than the amygdala, and could this higher variance drive the greater discovery in the sACC?

- [ ] Generate a figure that displays the variability of gene expression levels in sACC vs AMYG; perhaps boxplots of sigma^2 for each gene in sACC vs AMYG

---

Here I think that the simplest plot to make is a scatter plot (like in #8) between the `rowSds(RPKM)` computed for each region. `genefilter` and `matrixStats` implement that function.

**Comment by lcolladotor** [comment]
https://rdrr.io/cran/matrixStats/man/rowSds.html

This is a bit more complicated since it we'll have to do for every feature level like in #8. So RPKMs for genes and exons, RP80M (or was it RP10M?) for exon-exon junctions and TPMs for transcripts.

**Comment by andrewejaffe** [comment]
It's probably worth running levene test or another test of differential
variation comparing an equal number of controls from both brain regions.
Maybe on log rpkm scale  and then on the cleaningY output of full model
(sans Dx)?

**Comment by lcolladotor** [comment]
I like the idea of regressing out all the variability from the terms (covariates) we adjust for in the models, keeping only the Dx. 

I didn't remember the levene test https://en.wikipedia.org/wiki/Levene%27s_test, so that's a good idea =). Looks like `car::leveneTest()` can do the job http://www.sthda.com/english/wiki/compare-multiple-sample-variances-in-r.

**Comment by lcolladotor** [comment]
So, for every gene, extract `expr` from `cleaningY(rpkm, mod = joint_model, P = 3)` where we keep the `Dx` and `Region` effects. Define `dx_region_group` as a 4 level factor (2 regions, case/control Dx).

then use:

```R
library(car)
leveneTest(expr ~dx_region_group, data = data_for_one_gene)
```

**Comment by lcolladotor** [comment]
FYI I just finished editing my previous comment

**Comment by andrewejaffe** [comment]
/users/ajaffe/Lieber/lieber_functions_aj.R #1938
leveneFast()

**Comment by lcolladotor** [comment]
OHHH, thanks!

```R
leveneFast <- function(dat, groups) {
	require(matrixStats)
	N = length(groups)
	k = length(unique(groups))
	
	gIndexes = split(seq(along=groups),groups)
	gLens = as.numeric(sapply(gIndexes,length))

	zij = dat
	for(i in seq(along=gIndexes)) {
		ind = gIndexes[[i]]
		zij[,ind] = abs(dat[,ind] - rowMedians(dat[,ind]))
	}
	
	zdotdot = rowMeans(zij)
	zidot = sapply(gIndexes, function(x) rowMeans(zij[,x]))
	
	num = rowSums(gLens*(zidot-zdotdot)^2)
	
	out = zidot
	for(i in seq(along=gIndexes)) {
		ind = gIndexes[[i]]
		out[,i] = rowSums((zij[,ind] - zidot[,i])^2)
	}
	denom = rowSums(out)
	
	W = ((N-k)/(k-1))*(num/denom)
	pval = pf(W, df1 = k-1, df2 = N-k, lower.tail = FALSE)
	
	return(data.frame(cbind(W,pval)))
}
```


Louise, I see that `groups` would need to be a factor. So for `Dx * Region` it can be done with `groups = factor(paste0(Dx, "_", Region))` or something like that. `dat` would be the output from `cleaningY()`. You'll need to have `matrixStats` installed too.
