### ISSUE TITLE
Test for DE in marker genes used for deconvolution

### ISSUE THREAD

**Issue by lahuuki** [LieberInstitute/zandiHyde_bipolar_rnaseq#14]
Responding to concerns from reviewer 1, test for differential expression of genes between regions (sACC vs. Amyg) in the snRNA-seq for the set of marker genes we used.

**Comment by lcolladotor** [comment]
Check sections 14.3.2 and 14.3.3 from OSCA at https://bioconductor.org/books/release/OSCA/multi-sample-comparisons.html#performing-the-de-analysis.

Basically, we can use `pseudoBulkDGE()` on an SCE object with the sACC and AMY data to test for DE between brain region across each broad cell type.

**Comment by lcolladotor** [comment]
We can likely close this issue, right? Now that the paper has been published.
