### ISSUE TITLE
Preform Deconvolution with Bisque

### ISSUE THREAD

**Issue by lahuuki** [LieberInstitute/zandiHyde_bipolar_rnaseq#7]
- [x] Check all cellType markers are expressed
- [x] Run Bisque
- [x] Composition Bar plot
- [x] Box plot by Dx
- [x] prop vs. qSV values: grid and tiles
- [x] t-stats with 0.05 & 0.01 FDR cut offs
- [ ] top tables for DE with prop terms in model

**Comment by lahuuki** [comment]
Export top table - excel sheet with separate sheets for each region. Create separate files for prop and ilr models.

**Comment by lcolladotor** [comment]
For using `xlsx`, you need to request some more mem for Java before opening R like at https://github.com/LieberInstitute/brainseq_phase2/blob/e1a67fe8900ffcc637ad7f405b620dc15a93d4af/supp_tabs/twas_supp.R#L4-L5
